from decouple import config
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_API_TOKEN = config("TELEGRAM_API_TOKEN")
TELEGRAM_WEBHOOK_SECRET_KEY = config("TELEGRAM_WEBHOOK_SECRET_KEY")
TELEGRAM_WEBHOOK_HOST = config("TELEGRAM_WEBHOOK_HOST")
TELEGRAM_CONTECT_ID = config("TELEGRAM_CONTECT_ID")
UVICORN_PORT = config("UVICORN_PORT", cast=int, default=443)
UVICORN_SSL_CERTFILE = config("UVICORN_SSL_CERTFILE", default="")
UVICORN_SSL_KEYFILE = config("UVICORN_SSL_KEYFILE", default="")
